Fixes for compiling and others
RoootTheFox/celeste-ios pull request #13
Opened 2024-09-06 15:20 UTC by DelofJ

2024-09-06 19:18 UTC, RoootTheFox requested changes

2024-09-06 19:18 UTC, RoootTheFox commented on patches/crash-fixes.patch
These are too many changes, i can not in good faith merge this.

2024-09-09 05:17 UTC, RoootTheFox commented on patches/crash-fixes.patch
my issue is that the diff is huge - i want to apply as few modifications to Celeste as possible, which means I'd rather find out why MathF is broken for some people instead of patching half the game.

2024-10-19 20:51 UTC, Bryceshaw06 commented
This PR along with https://github.com/RoootTheFox/fnalibs-ios-builder-celeste/pull/2 fixed (most of the) the building issues for me! The only thing I had to do was run `sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer` 

in order to fix this: 

 `/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.Shared.targets(1746,3): error : Could not find a valid Xcode app bundle at '/Library/Developer/CommandLineTools' Please update your Apple SDK location in Visual Studio's preferences (Projects > SDK Locations > Apple > Apple SDK). `

Thank you for your hard work @RoootTheFox and @DelofJ !!!

The only thing I'm still struggling with is the touch controls not showing up. Seems like it might be related to this other build error. I'll open a separate GitHub issue for it though.
![Terminal on 10-19-2024 at 04 49PM@2x](https://github.com/user-attachments/assets/17cd244a-d8f0-4876-9c76-f60d8627db58)

2025-09-29 15:54 UTC, closed without merging